# An Action to build and deploy Web Arcs to https://live.arcs.dev
name: arcs-live

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 10.x

      - name: Install dependencies
        run: npm install

      - name: Run Typescript Tests
        run: tools/sigh test --all

      - name: Run deployment preparation script
        run: tools/deploy

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: PolymerLabs/arcs-live
          publish_dir: ./
          publish_branch: master
          cname: live.arcs.dev

